# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'client_card.ui'
#
# Created: Tue Jun 20 18:20:15 2017
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!
from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1032, 667)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.btn_save = QtGui.QPushButton(self.centralwidget)
        self.btn_save.setGeometry(QtCore.QRect(700, 560, 181, 71))
        self.btn_save.setObjectName(_fromUtf8("btn_save"))
        self.tbl_front = QtGui.QTableWidget(self.centralwidget)
        self.tbl_front.setGeometry(QtCore.QRect(10, 200, 481, 431))
        self.tbl_front.setSizeIncrement(QtCore.QSize(0, 0))
        self.tbl_front.setBaseSize(QtCore.QSize(0, 0))
        self.tbl_front.setRowCount(16)
        self.tbl_front.setColumnCount(4)
        self.tbl_front.setObjectName(_fromUtf8("tbl_front"))
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(9)
        item.setFont(font)
        item.setFlags(QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tbl_front.setItem(0, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tbl_front.setItem(0, 1, item)
        item = QtGui.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tbl_front.setItem(0, 2, item)
        item = QtGui.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tbl_front.setItem(0, 3, item)
        self.tbl_front.horizontalHeader().setVisible(False)
        self.tbl_front.horizontalHeader().setCascadingSectionResizes(False)
        self.tbl_front.horizontalHeader().setStretchLastSection(True)
        self.tbl_front.verticalHeader().setVisible(False)
        self.tbl_front.verticalHeader().setCascadingSectionResizes(False)
        self.tbl_front.verticalHeader().setDefaultSectionSize(20)
        self.tbl_front.verticalHeader().setHighlightSections(False)
        self.tbl_front.verticalHeader().setSortIndicatorShown(False)
        self.tbl_front.verticalHeader().setStretchLastSection(True)
        self.tbl_back2 = QtGui.QTableWidget(self.centralwidget)
        self.tbl_back2.setGeometry(QtCore.QRect(510, 300, 511, 231))
        self.tbl_back2.setSizeIncrement(QtCore.QSize(0, 0))
        self.tbl_back2.setBaseSize(QtCore.QSize(0, 0))
        self.tbl_back2.setRowCount(9)
        self.tbl_back2.setColumnCount(2)
        self.tbl_back2.setObjectName(_fromUtf8("tbl_back2"))
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(9)
        item.setFont(font)
        item.setFlags(QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tbl_back2.setItem(0, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tbl_back2.setItem(0, 1, item)
        self.tbl_back2.horizontalHeader().setVisible(False)
        self.tbl_back2.horizontalHeader().setCascadingSectionResizes(False)
        self.tbl_back2.horizontalHeader().setStretchLastSection(True)
        self.tbl_back2.verticalHeader().setVisible(False)
        self.tbl_back2.verticalHeader().setCascadingSectionResizes(False)
        self.tbl_back2.verticalHeader().setDefaultSectionSize(20)
        self.tbl_back2.verticalHeader().setHighlightSections(False)
        self.tbl_back2.verticalHeader().setSortIndicatorShown(False)
        self.tbl_back2.verticalHeader().setStretchLastSection(True)
        self.tbl_back1 = QtGui.QTableWidget(self.centralwidget)
        self.tbl_back1.setGeometry(QtCore.QRect(510, 40, 511, 221))
        self.tbl_back1.setSizeIncrement(QtCore.QSize(0, 0))
        self.tbl_back1.setBaseSize(QtCore.QSize(0, 0))
        self.tbl_back1.setRowCount(8)
        self.tbl_back1.setColumnCount(4)
        self.tbl_back1.setObjectName(_fromUtf8("tbl_back1"))
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(9)
        item.setFont(font)
        item.setFlags(QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tbl_back1.setItem(0, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tbl_back1.setItem(0, 1, item)
        item = QtGui.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tbl_back1.setItem(0, 2, item)
        item = QtGui.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tbl_back1.setItem(0, 3, item)
        self.tbl_back1.horizontalHeader().setVisible(False)
        self.tbl_back1.horizontalHeader().setCascadingSectionResizes(False)
        self.tbl_back1.horizontalHeader().setStretchLastSection(True)
        self.tbl_back1.verticalHeader().setVisible(False)
        self.tbl_back1.verticalHeader().setCascadingSectionResizes(False)
        self.tbl_back1.verticalHeader().setDefaultSectionSize(20)
        self.tbl_back1.verticalHeader().setHighlightSections(False)
        self.tbl_back1.verticalHeader().setSortIndicatorShown(False)
        self.tbl_back1.verticalHeader().setStretchLastSection(True)
        self.btn_search = QtGui.QPushButton(self.centralwidget)
        self.btn_search.setGeometry(QtCore.QRect(510, 560, 181, 71))
        self.btn_search.setObjectName(_fromUtf8("btn_search"))
        self.layoutWidget = QtGui.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(250, 10, 241, 25))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.gridLayout = QtGui.QGridLayout(self.layoutWidget)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label = QtGui.QLabel(self.layoutWidget)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.ln_house = QtGui.QLineEdit(self.layoutWidget)
        self.ln_house.setObjectName(_fromUtf8("ln_house"))
        self.gridLayout.addWidget(self.ln_house, 0, 1, 1, 1)
        self.label_5 = QtGui.QLabel(self.layoutWidget)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout.addWidget(self.label_5, 0, 2, 1, 1)
        self.ln_building = QtGui.QLineEdit(self.layoutWidget)
        self.ln_building.setObjectName(_fromUtf8("ln_building"))
        self.gridLayout.addWidget(self.ln_building, 0, 3, 1, 1)
        self.layoutWidget1 = QtGui.QWidget(self.centralwidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(12, 10, 231, 25))
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.gridLayout_2 = QtGui.QGridLayout(self.layoutWidget1)
        self.gridLayout_2.setMargin(0)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label_11 = QtGui.QLabel(self.layoutWidget1)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout_2.addWidget(self.label_11, 0, 0, 1, 1)
        self.ln_street = QtGui.QLineEdit(self.layoutWidget1)
        self.ln_street.setText(_fromUtf8(""))
        self.ln_street.setObjectName(_fromUtf8("ln_street"))
        self.gridLayout_2.addWidget(self.ln_street, 0, 1, 1, 1)
        self.layoutWidget2 = QtGui.QWidget(self.centralwidget)
        self.layoutWidget2.setGeometry(QtCore.QRect(250, 50, 241, 112))
        self.layoutWidget2.setObjectName(_fromUtf8("layoutWidget2"))
        self.gridLayout_4 = QtGui.QGridLayout(self.layoutWidget2)
        self.gridLayout_4.setMargin(0)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.label_6 = QtGui.QLabel(self.layoutWidget2)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_4.addWidget(self.label_6, 0, 0, 1, 1)
        self.ln_phone_home = QtGui.QLineEdit(self.layoutWidget2)
        self.ln_phone_home.setObjectName(_fromUtf8("ln_phone_home"))
        self.gridLayout_4.addWidget(self.ln_phone_home, 0, 1, 1, 1)
        self.label_7 = QtGui.QLabel(self.layoutWidget2)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_4.addWidget(self.label_7, 1, 0, 1, 1)
        self.ln_phone_mobile = QtGui.QLineEdit(self.layoutWidget2)
        self.ln_phone_mobile.setObjectName(_fromUtf8("ln_phone_mobile"))
        self.gridLayout_4.addWidget(self.ln_phone_mobile, 1, 1, 1, 1)
        self.label_8 = QtGui.QLabel(self.layoutWidget2)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_4.addWidget(self.label_8, 2, 0, 1, 1)
        self.ln_phone_work = QtGui.QLineEdit(self.layoutWidget2)
        self.ln_phone_work.setObjectName(_fromUtf8("ln_phone_work"))
        self.gridLayout_4.addWidget(self.ln_phone_work, 2, 1, 1, 1)
        self.label_9 = QtGui.QLabel(self.layoutWidget2)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_4.addWidget(self.label_9, 3, 0, 1, 1)
        self.ln_email = QtGui.QLineEdit(self.layoutWidget2)
        self.ln_email.setObjectName(_fromUtf8("ln_email"))
        self.gridLayout_4.addWidget(self.ln_email, 3, 1, 1, 1)
        self.label_10 = QtGui.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(510, 5, 491, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_10.setFont(font)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.label_12 = QtGui.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(510, 270, 441, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_12.setFont(font)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.btn_add_back1 = QtGui.QPushButton(self.centralwidget)
        self.btn_add_back1.setGeometry(QtCore.QRect(980, 260, 41, 31))
        self.btn_add_back1.setObjectName(_fromUtf8("btn_add_back1"))
        self.btn_add_back2 = QtGui.QPushButton(self.centralwidget)
        self.btn_add_back2.setGeometry(QtCore.QRect(980, 530, 41, 31))
        self.btn_add_back2.setObjectName(_fromUtf8("btn_add_back2"))
        self.spn_year = QtGui.QSpinBox(self.centralwidget)
        self.spn_year.setGeometry(QtCore.QRect(10, 170, 62, 31))
        self.spn_year.setMinimum(2017)
        self.spn_year.setMaximum(3000)
        self.spn_year.setProperty("value", 2017)
        self.spn_year.setObjectName(_fromUtf8("spn_year"))
        self.layoutWidget3 = QtGui.QWidget(self.centralwidget)
        self.layoutWidget3.setGeometry(QtCore.QRect(10, 50, 231, 112))
        self.layoutWidget3.setObjectName(_fromUtf8("layoutWidget3"))
        self.gridLayout_5 = QtGui.QGridLayout(self.layoutWidget3)
        self.gridLayout_5.setMargin(0)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.label_2 = QtGui.QLabel(self.layoutWidget3)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_3.addWidget(self.label_2, 0, 0, 1, 1)
        self.ln_surname = QtGui.QLineEdit(self.layoutWidget3)
        self.ln_surname.setObjectName(_fromUtf8("ln_surname"))
        self.gridLayout_3.addWidget(self.ln_surname, 0, 1, 1, 1)
        self.label_3 = QtGui.QLabel(self.layoutWidget3)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_3.addWidget(self.label_3, 1, 0, 1, 1)
        self.ln_name = QtGui.QLineEdit(self.layoutWidget3)
        self.ln_name.setObjectName(_fromUtf8("ln_name"))
        self.gridLayout_3.addWidget(self.ln_name, 1, 1, 1, 1)
        self.label_4 = QtGui.QLabel(self.layoutWidget3)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_3.addWidget(self.label_4, 2, 0, 1, 1)
        self.ln_secondname = QtGui.QLineEdit(self.layoutWidget3)
        self.ln_secondname.setObjectName(_fromUtf8("ln_secondname"))
        self.gridLayout_3.addWidget(self.ln_secondname, 2, 1, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_3, 0, 0, 1, 2)
        self.chck_is_member = QtGui.QCheckBox(self.layoutWidget3)
        self.chck_is_member.setObjectName(_fromUtf8("chck_is_member"))
        self.gridLayout_5.addWidget(self.chck_is_member, 1, 0, 1, 1)
        self.chck_is_rubbish = QtGui.QCheckBox(self.layoutWidget3)
        self.chck_is_rubbish.setObjectName(_fromUtf8("chck_is_rubbish"))
        self.gridLayout_5.addWidget(self.chck_is_rubbish, 1, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Карточка клиента", None))
        self.btn_save.setText(_translate("MainWindow", "Сохранить", None))
        __sortingEnabled = self.tbl_front.isSortingEnabled()
        self.tbl_front.setSortingEnabled(False)
        self.tbl_front.setSortingEnabled(__sortingEnabled)
        __sortingEnabled = self.tbl_back2.isSortingEnabled()
        self.tbl_back2.setSortingEnabled(False)
        self.tbl_back2.setSortingEnabled(__sortingEnabled)
        __sortingEnabled = self.tbl_back1.isSortingEnabled()
        self.tbl_back1.setSortingEnabled(False)
        self.tbl_back1.setSortingEnabled(__sortingEnabled)
        self.btn_search.setText(_translate("MainWindow", "Поиск", None))
        self.label.setText(_translate("MainWindow", "Дом:", None))
        self.label_5.setText(_translate("MainWindow", "Корпус:", None))
        self.label_11.setText(_translate("MainWindow", "Улица:      ", None))
        self.label_6.setText(_translate("MainWindow", "Дом. тел.:", None))
        self.label_7.setText(_translate("MainWindow", "Моб. тел.:", None))
        self.label_8.setText(_translate("MainWindow", "Раб. тел.:", None))
        self.label_9.setText(_translate("MainWindow", "Email:", None))
        self.label_10.setText(_translate("MainWindow", "Расшифровка задолженности на начало года", None))
        self.label_12.setText(_translate("MainWindow", "Целевые взносы (всего)", None))
        self.btn_add_back1.setText(_translate("MainWindow", "+", None))
        self.btn_add_back2.setText(_translate("MainWindow", "+", None))
        self.label_2.setText(_translate("MainWindow", "Фамилия:", None))
        self.label_3.setText(_translate("MainWindow", "Имя:", None))
        self.label_4.setText(_translate("MainWindow", "Отчество:", None))
        self.chck_is_member.setText(_translate("MainWindow", "Член ТСЖ", None))
        self.chck_is_rubbish.setText(_translate("MainWindow", "Вывоз мусора", None))

